### ISSUE TITLE
[openSUSE] RPMLINT warning  W: shared-lib-calls-exit

### ISSUE THREAD

**Issue by kevinsmia1939** [sunqm/libcint#41]
Hello,

I am trying to package libcint to openSUSE.
https://build.opensuse.org/package/show/home:andythe_great/libcint

I got a warning from RPMLINT as shown below.
```

libcint3.x86_64: W: shared-lib-calls-exit /usr/lib64/libcint.so.3.1.1 exit@GLIBC_2.2.5
This library package calls exit() or _exit(), probably in a non-fork()
context. Doing so from a library is strongly discouraged - when a library
function calls exit(), it prevents the calling program from handling the
error, reporting it to the user, closing files properly, and cleaning up any
state that the program has. It is preferred for the library to return an
actual error code and let the calling program decide how to handle the
situation.
```
Not sure what this meant.

Thank you.

**Comment by sunqm** [comment]
Thanks for bringing up the issue of exit(). I can understand the problem to call
exit() if users actually mean to handle an exception rather than terminate the
entire program.  I didn't find a proper solution for a C library so far.  The
function call to exit() will not be changed.

It's worthy to mention that when the exit conditions may be triggered.  In
two-electron integrals for basis with high angular moment (l >= 7) or high order
derivatives for basis with high angular momentum (e.g. 4th order derivatives for
basis l=6), exit() might be called if numerical singularity is caught in Rys
polynomials routines.  In regular quantum chemistry calculations, like DFT for
molecules and crystals, these extreme conditions can be ignored.

On Tue, Sep 01, 2020 at 02:59:51PM -0700, Kevin Tee wrote:
> Hello,
> 
> I am trying to package libcint to openSUSE.
> https://build.opensuse.org/package/show/home:andythe_great/libcint
> 
> I got a warning from RPMLINT as shown below.
> ```
> 
> libcint3.x86_64: W: shared-lib-calls-exit /usr/lib64/libcint.so.3.1.1 exit@GLIBC_2.2.5
> This library package calls exit() or _exit(), probably in a non-fork()
> context. Doing so from a library is strongly discouraged - when a library
> function calls exit(), it prevents the calling program from handling the
> error, reporting it to the user, closing files properly, and cleaning up any
> state that the program has. It is preferred for the library to return an
> actual error code and let the calling program decide how to handle the
> situation.
> ```
> Not sure what this meant.
> 
> Thank you.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sunqm/libcint/issues/41

--

**Comment by kevinsmia1939** [comment]
Alright thanks
