### ISSUE TITLE
Derivatives of the nuclear attraction integral

### ISSUE THREAD

**Issue by gustavojra** [sunqm/libcint#62]
My understanding is that there are two components to this derivative: ⟨i|∇nuc|j⟩ and ⟨i|nuc|∇j⟩. If that's the case I have a few questions on `libcint` usage:

- For basis function not centered on the atom being displaced, how do I compute the ⟨i|∇nuc|j⟩ contribution only? 

- When computing gradients with `cint1e_ipnuc_sph` is ⟨i|nuc|∇j⟩ the only term included?

Thank you!

**Comment by sunqm** [comment]
cint1e_ipnuc_sph is the derivatives of electron coordinates. You would need to transform it to derivatives of nuclear coordinates with a minus sign due to the bindings r - R between electron coordinates and nuclear coordinates in GTO basis. cint1e_ipnuc_sph only includes ⟨∇i|nuc|j⟩. You can transpose the integrals tensor to get ⟨i|nuc|∇j⟩ .Then computing ⟨i|∇_R nuc|j⟩ = -⟨∇_R i|nuc|j⟩ - ⟨i|nuc|∇_R j⟩ = ⟨∇ i|nuc|j⟩ + ⟨i|nuc|∇ j⟩

For basis off the atom center, derivatives can be computed with the similar indirect methods.
